dist: focal
                                                                                                                                                     
language: python                                                                                                                                                                                         
                                                                                                                                                                       
python:                                                                                                                                                                                                  
  - "3.8"

addons:
  sonarcloud:
    organization: paclaraujo
    token: ${SONAR_TOKEN}                                                                                                                                                                                              
                                                                                                                                          
install:                                                                                                                                                                                                 
  - pip install flask pytest
  - pip install flask pytest flask-wtf

script:                                                                                                                                                                                                  
  - pytest -v test.py
  - sonar-scanner || travis_terminate 1;

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  edge: true 
  app: devops-paloma
  on:
    branch: main